### PR TITLE
Steering code upload

### PR DESCRIPTION
**Pull request by yiqunma**
should have all protocols, configs, and scripts

### CODE REVIEW

**Comment by Surnus15** [comment]
Awesome! What about the embedding protocol? If you have it handy just toss it in there and I'll merge this pull into master.

This branch is a few commits behind master for some reason, not sure why, but it should be fine to merge.

**Comment by Surnus15** [comment]
Aight sounds good! 

hmmmm based on the commits missing I can guesstimate that one of two things happened:
1) The local clone of the master wasn't up to date when you branched. (Local repos unfortunately don't automatically update when the remote is updated.) 
2) Basically the same as 1 except you branched it from the Yiqun branch which may have been branched prior to some updates. If so it would have started in whatever state the Yiqun branch was at the branch point. 

Git takes a bit of getting used to and a bit of paranoid usage to have it work optimally. There's a fun visualizer somewhere on github that's a linear line/dot graph of all commits and branches of repositories. Can't find it off hand right now.

**Comment by yiqunma** [comment]
That makes a lot of sense. Since you updated the processing code recently, i can just cancel the pull request and redo the protocols from today. It won’t take long at all.

Yiqun

Yiqun (Quinn) Ma
B.S. Biomedical Engineering
UW Madison 2019’
yma99@wisc.edu

________________________________

**Comment by Surnus15** [comment]
Git wouldn't be fantastic if ya had to do that. It should just be able to automatically merge despite lagging a bit since your commits only affect files/folders that haven't been messed with at all in the missing commits.

**Comment by yiqunma** [comment]
Sounds great! I’ll get to the embedding protocol in just a bit. Thanks for all the info!
Yiqun

Yiqun (Quinn) Ma
B.S. Biomedical Engineering
UW Madison 2019’
yma99@wisc.edu

________________________________

**Comment by Surnus15** [comment]
I.e. that's what it means with This branch has no conflicts with the base branch. 

That said if we both messed with the same file we would need to review the respective changes/conflicts and decide what to keep, and/or squash the missing commits (revert them to the branch point and use this branch as the new master), or rebase and merge which tries to implement all the new commits sequentially at the end of the current master branch. [(Here's a good explanation of the difference between merge vs. rebase and merge.)](https://hackernoon.com/git-merge-vs-rebase-whats-the-diff-76413c117333)

**Comment by Surnus15** [comment]
Aight everything looks good! Gimme a sec to merge this and delete the branch here before you delete your local Steering-code-upload branch.

**Comment by yiqunma** [comment]
Awesome! This does takes a bit to get used to, but how it works is really interesting and unique.

**Pull request merged**
