### PR TITLE
Seti Processing Code

### PR DESCRIPTION
**Pull request by Surnus15**
I am restructuring the repo to make it viable for inclusion in a future publication. As such I've moved all the old code to a separate folder in the directory and will be going through them as I upload my cleaned and commented processing code to integrate their functionality with my scripts. This is also setting up the repo's structure for including our steering scripts in a user-friendly manner.

### CODE REVIEW

**Comment by ctrueden** [comment]
@Surnus15 I do not know much about this repository, so as far as I'm concerned, you have carte blanche to make whatever changes you need. Feel free to self-merge if that makes your life easier. If you have specific questions or things you'd like review feedback on, let me know and I can take a look.

**Comment by Surnus15** [comment]
@ctrueden I'll freely admit that my exposure to git has been rather limited to date, but I'm guessing self-merge means I can just go ahead and merge whatever I feel like without needing to wait for review from someone else? For the most part this is Mach3 and Matlab scripts Yiquan and I have respectively already developed and just need to clean, but I'll add a note if there's a specific thing to review in future pull requests. Also is there a specific license statement I should be using with public files for an in-progress project such as this?

**Comment by ctrueden** [comment]
> I can just go ahead and merge whatever I feel like without needing to wait for review from someone else?

Yep.

> is there a specific license statement I should be using with public files for an in-progress project such as this?

My preference is for open source licensing. Check out https://choosealicense.com/

**Comment by Surnus15** [comment]
Repo restructured, licenses added, SIM Pattern Generator added, and Microscope Configuration File Editor added.

**Pull request merged**
